### ISSUE TITLE
remove ability to jump twice after walking off a ledge

### ISSUE THREAD

**Issue by jackiekircher** [ColourTann/gug#9]
if you walk off of a ledge you still get both your jumps. while this is fun, the main peril is falling. being able to jump back up to a ledge you just fell off of removes the punishment.

**Comment by ColourTann** [comment]
It would be very frustrating to try to time a tricky jump and fuck it up by one frame. If we do remove this, we should allow 3-4 grace frames on doing a full jump

**Comment by ColourTann** [comment]
I think we shouldn't fix this, it's fine!
